### ISSUE TITLE
Expose `auto_organize_prefix` in `WorkspaceSettings`

### ISSUE THREAD

**Issue by miterion** [wandb/wandb-workspaces#10]
I would like to pro grammatically setup a Workspace mirroring one of our manually created workspaces. We use the "Group first prefix" setting, which is not the default and can't be set using the currently exposed API. 

I looked through the "internal" code and it seems that `auto_organize_prefix` is responsible for setting this in the API.  https://github.com/wandb/wandb-workspaces/blob/6000559bbea55c514ce85bd5aced22e861324e9d/wandb_workspaces/reports/v2/internal.py#L186-L186

Would it be possible to expose this setting as part of `WorkspaceSettings` to be set by the user when creating/updating a workspace?

<details>
<summary>Group by first prefix in the UI</summary>

![image](https://github.com/wandb/wandb-workspaces/assets/4395770/7dc01228-2bac-4095-942b-f17993b7bdba)
</details>

**Comment by andrewtruong** [comment]
Hey @miterion, can you expand on how you want to do mirroring?

We didn't expose this initially it could create ambiguous state, e.g.:
1. User sets the auto-organize flag; and
2. User manually specifies order in sections and panels

By mirroring I'm imagining you want to have pre-defined section order, but the panels may be different?  In that case maybe we can expose this but just give a warning to the user that the order might not be what they explicitly specified

**Comment by miterion** [comment]
> Hey @miterion, can you expand on how you want to do mirroring?

Yes, sure thing. We have a workspace that contains a few sections that are hand-curated and pinned. The rest of the sections is automatically generated and sorted using the "Group by first prefix" setting. It would be great if we could reproduce this using the workspace API.
