### ISSUE TITLE
[Q] Programmatically fetch all blocks of all reports

### ISSUE THREAD

**Issue by SauravMaheshkar** [wandb/wandb-workspaces#14]
Hi 👋🏽, I was wondering if there is any way to use the wandb API and workspaces together to fetch all the blocks of all the reports I have authored. 

## References
* https://github.com/wandb/wandb/issues/7703

**Comment by andrewtruong** [comment]
I think you can query for Reports from the vanilla W&B API, and there should be a `url` property.

Then you can iterate to get the blocks you need:
```py
urls = [...]

def get_all_blocks(urls: list[str]):
  for url in urls:
    report = wr.Report.from_url(url)
    yield from report.blocks
```
